server:
  port: 10087
spring:
  application:
    name: server
eureka:
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: true #不将自己注册到注册中心
    fetch-registry: true #不从注册中心拉取注册表
    service-url:
      defaultZone: http://localhost:10086/eureka
