server:
  port: 8888
spring:
  application:
    name: gateway
#zuul:
#  routes:
#    user:
#      path: /weixiu/**
#      serviceId: feign
  cloud:
    gateway:
      routes:
        - id: feign
          uri: lb://feign
          order: 0
          predicates:
            - Path=/weixiu/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/,http://localhost:10087/eureka/