spring:
  application:
    name: weixiu
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/1703a_springcloud?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hefeifei.entity
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
    fetch-registry: true  #作为微服务的消费方，务必将此项设置为true，表示可以从注册中心拉取微服务的注册表从而获取提供方的地址
